### ISSUE TITLE
Typo of word "magical"

### ISSUE THREAD

**Issue by tye-exe** [Evertras/simple-homemanager#5]
The word "magical" seem to have been typed with the typo "mgaical" the file 05 at line 192. [Link to line.](https://github.com/Evertras/simple-homemanager/blob/a4f496c3e8af2f11a19f219e6f987965f71b1c80/05-explain-outputs-body.md?plain=1#L192)
Sorry if this is a bit of a nitpick. I love this guide, it's a beautiful introduction to nixos!

**Comment by Evertras** [comment]
Whops, good catch.  Fixed!  Not a nitpick, typos make things annoying to read.  Glad you liked the guide!
